site_name: "UVSQ_M2_NewSpace_TP_Python"
site_url: "https://nicoudart.github.io/UVSQ_M2_NewSpace_TP_signal"
site_author: "Nicolas OUDART"

theme:
  name: readthedocs
nav:
  - Accueil: index.md
  - TP ROXI: TP_ROXI.md
  - TP RIMFAX: TP_RIMFAX.md